[2025-03-17T17:31:53.622+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_dag.s3_upload manual__2025-03-17T17:22:59.507573+00:00 [queued]>
[2025-03-17T17:31:53.626+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_dag.s3_upload manual__2025-03-17T17:22:59.507573+00:00 [queued]>
[2025-03-17T17:31:53.626+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2025-03-17T17:31:53.630+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2025-03-17 17:22:59.507573+00:00
[2025-03-17T17:31:53.633+0000] {standard_task_runner.py:57} INFO - Started process 73 to run task
[2025-03-17T17:31:53.635+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_dag', 's3_upload', 'manual__2025-03-17T17:22:59.507573+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpba8thpqo']
[2025-03-17T17:31:53.637+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask s3_upload
[2025-03-17T17:31:53.658+0000] {task_command.py:416} INFO - Running <TaskInstance: reddit_dag.s3_upload manual__2025-03-17T17:22:59.507573+00:00 [running]> on host 2d638ef189c1
[2025-03-17T17:31:53.686+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='rajagopalanr0210@gmail.com' AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='reddit_dag' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T17:22:59.507573+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-17T17:22:59.507573+00:00'
[2025-03-17T17:31:55.106+0000] {logging_mixin.py:151} INFO - Bucket already exists
[2025-03-17T17:31:55.983+0000] {aws_etl.py:29} ERROR - Error in upload_to_s3: Access Denied
[2025-03-17T17:31:55.985+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-03-17T17:31:56.009+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reddit_dag, task_id=s3_upload, execution_date=20250317T172259, start_date=20250317T173153, end_date=20250317T173156
[2025-03-17T17:31:56.069+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-17T17:31:56.078+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
